---
- hosts: all
  become: true
  tasks:
    - name: Atualizar o cache de pacotes
      apt:
        update_cache: yes

    - name: Atualizar pacotes com upgrade
      apt:
        upgrade: yes
        update_cache: yes

    - name: Realizar dist-upgrade
      command: apt-get dist-upgrade -y
